### ISSUE TITLE
BUG: K-Element pins swapped

### ISSUE THREAD

**Issue by Quas7** [DurandA/reflow946#7]
I had to swap + ans - at my K element connector to get correct polarity. No big deal but rotating the connector socket would fix this.

**Comment by DurandA** [comment]
Hi @Quas7 👋 and thanks for the feedback.

On my unit the connector has the right polarity. Can you post a picture of your original control board?

**Comment by DurandA** [comment]
This is a mistake that was introduced with the Kicad version (rev 1.1):
![image](https://github.com/DurandA/reflow946/assets/3709037/82b28fc0-bd5f-42a3-aa7d-d3e95903550d)
 
On rev 1.0 the MAX31855K is connected differently:
![image](https://github.com/DurandA/reflow946/assets/3709037/7cf4ec1a-0a75-4347-bc42-bc5fb0e5e6e8)

Since I am still using the rev 1.0 and never assembled a rev 1.1, this went unnoticed. I will collect other issues and make a new revision.

**Comment by DurandA** [comment]
Fixed in 5f84cfc61181377c1e6a4e7759f00b89bdffa89a. Thank you very much for raising this issue.
